### ISSUE TITLE
Consider supporting `--force` for forcing a deployment past unfinished CI statuses

### ISSUE THREAD

**Issue by gjtorikian** [aseriousbiz/abbot-skills#17]
Hiya. I'd make this a PR, except I have a hacky setup on my current skill—I'm not sure how to parse optional arguments coming in.

But, if you set an empty collection of contexts, Abbot will allow you to create a force deploy:

```csharp
    if (forced) {
        await Bot.ReplyAsync("Forced? I hope you know what you're doing...");
        deployment.RequiredContexts = new Collection<string>();
    }
```

My way of setting `forced` is what's keeping me from just making the PR: `var forced = Bot.Arguments.Any(a => a.ToString() == "--force");`

**Comment by haacked** [comment]
@gjtorikian that seems like a good approach.

I'd make one small adjustment:

```csharp
var forced = Bot.Arguments.Any(a => a.Value == "--force");
```

**Comment by haacked** [comment]
Oh wait, because of the way we do pattern matching, that won't work. I'll see if I can put something together.

**Comment by haacked** [comment]
Ok, I pushed a change to `deploy` that adds force deploys. It uses a new method `FindAndRemove`. The point of the method is to find an argument by a condition and return the rest of the args without that argument. It's a pattern for optional args so that the rest of the arg parsing doesn't have to change. Hope that helps!

**Comment by gjtorikian** [comment]
Thanks!
